apiVersion: v1
kind: Pod
metadata:
  name: consumer-service
  labels:
    app: consumer-service
    owner: zbio
    managed-by: roost
spec:
  containers:
  - name: consumer
    image: consumer:latest
    ports:
      - containerPort: 8091
    # env:
    # - name: SERVICE_ADDRESS
    #   value: zbio-service.zbio:50002
    # - name: BROKER_POD_NAME
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: status.podIP
    imagePullPolicy: Never
    # resources:
    #   requests: {}
    #   limits:
    #     memory: "256Mi"
    #     cpu: "200m"
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0

---
kind: Service 
apiVersion: v1
metadata:
  name: consumer-service
  labels:
    app: consumer-service
    owner: zbio
    managed-by: roost
spec:
  type: NodePort
  selector:
    app: consumer-service
  ports:
  - name: tcp
    port: 8091
    targetPort: 8091
    nodePort: 30045
